# Generated by Django 2.2.4 on 2023-06-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos_Ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
