# Generated by Django 2.2.4 on 2023-06-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0003_auto_20230619_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='interesting course'),
        ),
    ]
